<pre>
/*
==============================================================================
QC script generated by http://jday.in.ua MDL View 1.0
<?=Date('Y');?>, Jday. Based on code from Valve's HL SDK.

<?=$model->filename.PHP_EOL;?>

Original internal name:
<?='"'.$model->header->name.'"'.PHP_EOL;?>

==============================================================================
*/

$modelname "<?=$model->filename;?>"

$cd ".\"
$cdtexture ".\"
$scale 1.0
$cliptotextures

<?php
foreach($model->studioBoxes as $bbox) {	echo '$bbox '.$bbox->bbmin->x.' '.$bbox->bbmin->y.' '.$bbox->bbmin->z.' '.$bbox->bbmax->x.' '.$bbox->bbmax->y.' '.$bbox->bbmax->z.PHP_EOL;}
?>

$eyeposition <?php echo $model->header->eyeposition->x.' '.$model->header->eyeposition->y.' '.$model->header->eyeposition->z.PHP_EOL?>




// <?php echo $model->header->numskinfamilies;?> skin families
$texturegroup skinfamilies
{
{ "gensoda1.bmp" }
{ "gensoda2.bmp" }
{ "gensoda3.bmp" }
{ "gensoda4.bmp" }
{ "gensoda5.bmp" }
{ "gensoda6.bmp" }
}
<!--
$bbox 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000
$cbox 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000
$eyeposition 0.000000 0.000000 0.000000


//reference mesh(es)
$body "can" "gensoda1"


// 6 skin families
$texturegroup skinfamilies
{
{ "gensoda1.bmp" }
{ "gensoda2.bmp" }
{ "gensoda3.bmp" }
{ "gensoda4.bmp" }
{ "gensoda5.bmp" }
{ "gensoda6.bmp" }
}

// 1 hit box(es)
$hbox 0 "Cylinder01" -3.370000 -3.660000 0.000000 3.750000 3.650000 13.450000

// 1 animation sequence(s)
$sequence "idle" "idle" fps 30

// End of QC script.
-->
</pre>